# Generated by Django 4.1 on 2022-10-28 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0002_profile_rename_isfinished_transaction_isfinished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 1, 55, 0, 13965, tzinfo=datetime.timezone.utc)),
        ),
    ]
