# Generated by Django 4.1 on 2022-10-28 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0002_alter_feedback_date_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='location',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 20, 13, 18, 543659, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 20, 13, 18, 542632, tzinfo=datetime.timezone.utc)),
        ),
    ]
