# Generated by Django 4.1 on 2022-10-29 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0002_alter_feedback_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 14, 30, 22, 89912, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 14, 30, 22, 88946, tzinfo=datetime.timezone.utc)),
        ),
    ]
