# Generated by Django 4.1 on 2022-10-28 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('intro', models.TextField()),
                ('image', models.CharField(max_length=500)),
                ('news', models.TextField()),
                ('source', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 28, 17, 44, 56, 378383))),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 17, 44, 56, 377352)),
        ),
    ]
