# Generated by Django 4.1 on 2022-10-28 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('intro', models.TextField()),
                ('image', models.CharField(max_length=500)),
                ('date_published', models.DateField()),
                ('content', models.TextField()),
                ('source', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 28, 3, 45, 8, 874623, tzinfo=datetime.timezone.utc))),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 3, 45, 8, 873593, tzinfo=datetime.timezone.utc)),
        ),
    ]
