# Generated by Django 4.1 on 2022-10-28 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0004_article_feedback_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_published',
            new_name='publish_date',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 3, 46, 34, 535512, tzinfo=datetime.timezone.utc)),
        ),
    ]
