# Generated by Django 4.1 on 2022-10-28 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0006_remove_article_image_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 4, 8, 53, 550826, tzinfo=datetime.timezone.utc)),
        ),
    ]
