# Generated by Django 4.1 on 2022-10-28 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0007_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 4, 41, 22, 248235, tzinfo=datetime.timezone.utc)),
        ),
    ]
