# Generated by Django 4.1 on 2022-10-28 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0009_alter_article_slug_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 6, 33, 51, 202735, tzinfo=datetime.timezone.utc)),
        ),
    ]
