# Generated by Django 4.1 on 2022-10-28 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bin_bank', '0010_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 6, 34, 15, 438773, tzinfo=datetime.timezone.utc)),
        ),
    ]
